language: bash
dist: xenial
#language: java

sudo: required

notifications:
  webhooks: https://hook.bearychat.com/=bwBrp/travis/93d020f67c0a20049466b93a0211692c

services:
  - docker

branches:
  only:
    - master
    - dev
    - release

jobs:
  include:
    - stage: deploy
      script:
        - cd src/docker
        - docker build --no-cache -f Dockerfile -t clouthinkin/helloworld:eureka --rm=true ../..
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push clouthinkin/helloworld:eureka
        - docker logout

stages:
  - name: deploy
    if: branch = master