language: bash
dist: xenial
#language: java

sudo: required

services:
  - docker

branches:
  only:
    - master
    - dev
    - release

jobs:
  include:
    - stage: deploy
      script:
        - cd src/docker
        - docker build --no-cache -f Dockerfile -t clouthinkin/helloworld:eureka --rm=true ../..
        - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
        - docker push clouthinkin/helloworld:eureka
        - docker logout
    - stage: build
      script:
        - ./gradlew clean build -x test

stages:
  - name: deploy
    if: branch = master
  - name: build
    if: branch = dev